export const FETCH_QUIZLES_START = "FETCH_QUIZLES_START";
export const FETCH_QUIZLES_SUCCESS = "FETCH_QUIZLES_SUCCESS";
export const FETCH_QUIZLES_ERROR = "FETCH_QUIZLES_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";

export const QUIZ_SET_STATE = "QUIZ_SET_STATE";
